module RDF
  ##
  # Schema.org (FOAF) vocabulary.
  #
  # Creating this involves extrating class and property definitions
  # from http://schema.org/docs/schema_org_rdfa.html, which is done
  # though the private class-method {SCHEMA.generate}
  #
  # @see http://schema.org/
  class SCHEMA < Vocabulary("http://schema.org/")
    
    property :about
    property :acceptedPaymentMethod
    property :acceptsReservations
    property :accountablePerson
    property :acquiredFrom
    property :action
    property :activeIngredient
    property :activityDuration
    property :activityFrequency
    property :actor
    property :actors
    property :additionalName
    property :additionalType
    property :additionalVariable
    property :addOn
    property :address
    property :addressCountry
    property :addressLocality
    property :addressRegion
    property :administrationRoute
    property :advanceBookingRequirement
    property :adverseOutcome
    property :affectedBy
    property :affiliation
    property :agent
    property :aggregateRating
    property :album
    property :albums
    property :alcoholWarning
    property :algorithm
    property :alignmentType
    property :alternateName
    property :alternativeHeadline
    property :alumni
    property :alumniOf
    property :amountOfThisGood
    property :antagonist
    property :applicableLocation
    property :applicationCategory
    property :applicationSubCategory
    property :applicationSuite
    property :appliesToDeliveryMethod
    property :appliesToPaymentMethod
    property :arterialBranch
    property :articleBody
    property :articleSection
    property :aspect
    property :assembly
    property :assemblyVersion
    property :associatedAnatomy
    property :associatedArticle
    property :associatedMedia
    property :associatedPathophysiology
    property :attendee
    property :attendees
    property :audience
    property :audio
    property :author
    property :availability
    property :availabilityEnds
    property :availabilityStarts
    property :availableAtOrFrom
    property :availableDeliveryMethod
    property :availableIn
    property :availableService
    property :availableStrength
    property :availableTest
    property :award
    property :awards
    property :background
    property :baseSalary
    property :benefits
    property :bestRating
    property :billingIncrement
    property :biomechnicalClass
    property :birthDate
    property :bitrate
    property :blogPost
    property :blogPosts
    property :bloodSupply
    property :bodyLocation
    property :bookEdition
    property :bookFormat
    property :borrower
    property :box
    property :branch
    property :branchOf
    property :brand
    property :breadcrumb
    property :breastfeedingWarning
    property :browserRequirements
    property :businessFunction
    property :buyer
    property :byArtist
    property :calories
    property :candidate
    property :caption
    property :carbohydrateContent
    property :carrierRequirements
    property :catalog
    property :category
    property :cause
    property :causeOf
    property :childMaxAge
    property :childMinAge
    property :children
    property :cholesterolContent
    property :circle
    property :citation
    property :clincalPharmacology
    property :closes
    property :code
    property :codeRepository
    property :codeValue
    property :codingSystem
    property :colleague
    property :colleagues
    property :collection
    property :color
    property :comment
    property :commentText
    property :commentTime
    property :comprisedOf
    property :connectedTo
    property :contactPoint
    property :contactPoints
    property :contactType
    property :containedIn
    property :contentLocation
    property :contentRating
    property :contentSize
    property :contentUrl
    property :contraindication
    property :contributor
    property :cookingMethod
    property :cookTime
    property :copyrightHolder
    property :copyrightYear
    property :cost
    property :costCategory
    property :costCurrency
    property :costOrigin
    property :costPerUnit
    property :countriesNotSupported
    property :countriesSupported
    property :course
    property :creator
    property :currenciesAccepted
    property :dataset
    property :dateCreated
    property :dateline
    property :dateModified
    property :datePosted
    property :datePublished
    property :dayOfWeek
    property :deathDate
    property :deliveryLeadTime
    property :deliveryMethod
    property :dependencies
    property :depth
    property :description
    property :device
    property :diagnosis
    property :diagram
    property :diet
    property :dietFeatures
    property :differentialDiagnosis
    property :director
    property :discusses
    property :discussionUrl
    property :distance
    property :distinguishingSign
    property :distribution
    property :domainIncludes
    property :dosageForm
    property :doseSchedule
    property :doseUnit
    property :doseValue
    property :downloadUrl
    property :drainsTo
    property :drug
    property :drugClass
    property :drugUnit
    property :duns
    property :duplicateTherapy
    property :duration
    property :durationOfWarranty
    property :editor
    property :educationalAlignment
    property :educationalFramework
    property :educationalRole
    property :educationalUse
    property :educationRequirements
    property :elevation
    property :eligibleCustomerType
    property :eligibleDuration
    property :eligibleQuantity
    property :eligibleRegion
    property :eligibleTransactionVolume
    property :email
    property :embedUrl
    property :employee
    property :employees
    property :employmentType
    property :encodesCreativeWork
    property :encoding
    property :encodingFormat
    property :encodings
    property :endDate
    property :endorsee
    property :endorsers
    property :endTime
    property :entertainmentBusiness
    property :epidemiology
    property :episode
    property :episodeNumber
    property :episodes
    property :equal
    property :estimatesRiskOf
    property :event
    property :events
    property :evidenceLevel
    property :evidenceOrigin
    property :exercisePlan
    property :exerciseType
    property :exifData
    property :expectedPrognosis
    property :experienceRequirements
    property :expertConsiderations
    property :expires
    property :familyName
    property :fatContent
    property :faxNumber
    property :featureList
    property :fiberContent
    property :fileFormat
    property :fileSize
    property :followee
    property :follows
    property :followup
    property :foodEstablishment
    property :foodEvent
    property :foodWarning
    property :founder
    property :founders
    property :foundingDate
    property :frequency
    property :fromLocation
    property :function
    property :functionalClass
    property :gender
    property :genre
    property :geo
    property :givenName
    property :globalLocationNumber
    property :greater
    property :greaterOrEqual
    property :gtin13
    property :gtin14
    property :gtin8
    property :guideline
    property :guidelineDate
    property :guidelineSubject
    property :hasPOS
    property :headline
    property :healthCondition
    property :height
    property :highPrice
    property :hiringOrganization
    property :homeLocation
    property :honorificPrefix
    property :honorificSuffix
    property :hospitalAffiliation
    property :howPerformed
    property :identifyingExam
    property :identifyingTest
    property :illustrator
    property :image
    property :imagingTechnique
    property :inAlbum
    property :incentives
    property :includedRiskFactor
    property :includesObject
    property :increasesRiskOf
    property :indication
    property :industry
    property :infectiousAgent
    property :infectiousAgentClass
    property :ingredients
    property :inLanguage
    property :inPlaylist
    property :insertion
    property :installUrl
    property :instrument
    property :intensity
    property :interactingDrug
    property :interactionCount
    property :interactivityType
    property :inventoryLevel
    property :isAccessoryOrSparePartFor
    property :isAvailableGenerically
    property :isBasedOnUrl
    property :isbn
    property :isConsumableFor
    property :isFamilyFriendly
    property :isicV4
    property :isPartOf
    property :isProprietary
    property :isRelatedTo
    property :isSimilarTo
    property :isVariantOf
    property :itemCondition
    property :itemListElement
    property :itemListOrder
    property :itemOffered
    property :itemReviewed
    property :jobLocation
    property :jobTitle
    property :keywords
    property :knows
    property :labelDetails
    property :landlord
    property :language
    property :lastReviewed
    property :latitude
    property :learningResourceType
    property :legalName
    property :legalStatus
    property :lender
    property :lesser
    property :lesserOrEqual
    property :line
    property :location
    property :logo
    property :longitude
    property :loser
    property :lowPrice
    property :mainContentOfPage
    property :makesOffer
    property :manufacturer
    property :map
    property :maps
    property :maximumIntake
    property :maxPrice
    property :maxValue
    property :mechanismOfAction
    property :medicalSpecialty
    property :medicineSystem
    property :member
    property :memberOf
    property :members
    property :memoryRequirements
    property :mentions
    property :menu
    property :minPrice
    property :minValue
    property :model
    property :mpn
    property :musicBy
    property :musicGroupMember
    property :naics
    property :name
    property :nationality
    property :naturalProgression
    property :nerve
    property :nerveMotor
    property :nonEqual
    property :nonProprietaryName
    property :normalRange
    property :numberOfEpisodes
    property :numberOfPages
    property :numTracks
    property :nutrition
    property :object
    property :occupationalCategory
    property :offerCount
    property :offers
    property :openingHours
    property :openingHoursSpecification
    property :opens
    property :operatingSystem
    property :oponent
    property :option
    property :origin
    property :originatesFrom
    property :outcome
    property :overdosage
    property :overview
    property :ownedFrom
    property :ownedThrough
    property :owns
    property :parent
    property :parents
    property :participant
    property :partOfSeason
    property :partOfSystem
    property :partOfTVSeries
    property :pathophysiology
    property :paymentAccepted
    property :performer
    property :performerIn
    property :performers
    property :permissions
    property :phase
    property :photo
    property :photos
    property :physiologicalBenefits
    property :playerType
    property :polygon
    property :population
    property :possibleComplication
    property :possibleTreatment
    property :postalCode
    property :postOfficeBoxNumber
    property :postOp
    property :predecessorOf
    property :pregnancyCategory
    property :pregnancyWarning
    property :preOp
    property :preparation
    property :prepTime
    property :prescribingInfo
    property :prescriptionStatus
    property :price
    property :priceCurrency
    property :priceRange
    property :priceSpecification
    property :priceType
    property :priceValidUntil
    property :primaryImageOfPage
    property :primaryPrevention
    property :printColumn
    property :printEdition
    property :printPage
    property :printSection
    property :procedure
    property :procedureType
    property :processorRequirements
    property :producer
    property :productID
    property :productionCompany
    property :proficiencyLevel
    property :programmingLanguage
    property :programmingModel
    property :proprietaryName
    property :proteinContent
    property :provider
    property :publicationType
    property :publisher
    property :publishingPrinciples
    property :purpose
    property :qualifications
    property :query
    property :question
    property :rangeIncludes
    property :ratingCount
    property :ratingValue
    property :realEstateAgent
    property :recipe
    property :recipeCategory
    property :recipeCuisine
    property :recipeInstructions
    property :recipeYield
    property :recipient
    property :recognizingAuthority
    property :recommendationStrength
    property :recommendedIntake
    property :regionDrained
    property :regionsAllowed
    property :relatedAnatomy
    property :relatedCondition
    property :relatedDrug
    property :relatedLink
    property :relatedStructure
    property :relatedTherapy
    property :relatedTo
    property :releaseDate
    property :releaseNotes
    property :relevantSpecialty
    property :repetitions
    property :replacee
    property :replacer
    property :replyToUrl
    property :representativeOfPage
    property :requirements
    property :requiresSubscription
    property :responsibilities
    property :restPeriods
    property :result
    property :resultReview
    property :review
    property :reviewBody
    property :reviewCount
    property :reviewedBy
    property :reviewRating
    property :reviews
    property :riskFactor
    property :risks
    property :runsTo
    property :runtime
    property :safetyConsideration
    property :salaryCurrency
    property :sameAs
    property :sampleType
    property :saturatedFatContent
    property :scheduledTime
    property :screenshot
    property :season
    property :seasonNumber
    property :seasons
    property :secondaryPrevention
    property :seeks
    property :seller
    property :sender
    property :sensoryUnit
    property :serialNumber
    property :seriousAdverseOutcome
    property :servesCuisine
    property :servingSize
    property :sibling
    property :siblings
    property :signDetected
    property :significance
    property :significantLink
    property :significantLinks
    property :signOrSymptom
    property :skills
    property :sku
    property :sodiumContent
    property :softwareVersion
    property :source
    property :sourcedFrom
    property :sourceOrganization
    property :spatial
    property :specialCommitments
    property :specialty
    property :sponsor
    property :sportsActivityLocation
    property :sportsEvent
    property :sportsTeam
    property :spouse
    property :stage
    property :stageAsNumber
    property :startDate
    property :startTime
    property :status
    property :storageRequirements
    property :streetAddress
    property :strengthUnit
    property :strengthValue
    property :structuralClass
    property :study
    property :studyDesign
    property :studyLocation
    property :studySubject
    property :subEvent
    property :subEvents
    property :subStageSuffix
    property :subStructure
    property :subTest
    property :subtype
    property :successorOf
    property :sugarContent
    property :suggestedGender
    property :suggestedMaxAge
    property :suggestedMinAge
    property :superEvent
    property :supplyTo
    property :targetDescription
    property :targetName
    property :targetPlatform
    property :targetPopulation
    property :targetProduct
    property :targetUrl
    property :taxID
    property :telephone
    property :temporal
    property :text
    property :thumbnail
    property :thumbnailUrl
    property :tickerSymbol
    property :timeRequired
    property :tissueSample
    property :title
    property :toLocation
    property :totalTime
    property :track
    property :tracks
    property :trailer
    property :transcript
    property :transFatContent
    property :transmissionMethod
    property :trialDesign
    property :tributary
    property :typeOfGood
    property :typicalAgeRange
    property :typicalTest
    property :unitCode
    property :unsaturatedFatContent
    property :uploadDate
    property :url
    property :usedToDiagnose
    property :usesDevice
    property :validFrom
    property :validThrough
    property :value
    property :valueAddedTaxIncluded
    property :valueReference
    property :vatID
    property :vendor
    property :version
    property :video
    property :videoFrameSize
    property :videoQuality
    property :warning
    property :warranty
    property :warrantyPromise
    property :warrantyScope
    property :weight
    property :width
    property :winner
    property :wordCount
    property :workHours
    property :workload
    property :workLocation
    property :worksFor
    property :worstRating

    private
    def self.generate
      require 'addressable/uri'
      require 'rdf/rdfa'
      v = Graph.load("http://schema.org/docs/schema_org_rdfa.html", :format => :rdfa)

      # properties
      v.query(:property => RDF.type, :object => RDF.Property) do |c|
        puts "    property #{c.subject.to_s.split('/').last.to_sym.inspect}"
      end
    end
  end
end
